# docker-compose.prod.yml (Production Override)
version: '3.8'

services:
  hls-proxy:
    ports:
      - "8000:8000"
    env_file:
      # IMPORTANTE: Este archivo .env.production no debe subirse a Git.
      - ./.env.production
    restart: unless-stopped